### ISSUE TITLE
Add an operation to make batch uploads easier

### ISSUE THREAD

**Issue by BendyWalker** [3squared/PeakNetwork#10]
I've encountered situations where, given an array of `Encodables`, I need to upload each one in an individual request to the web service I'm working with. It would be nice if PeakNetwork had an operation that took a `Requestable` and an array of `Codables` and performed a request for each one.

**Comment by blork** [comment]
There currently aren't many conveniences for uploading (POST/PUT) in the framework. This is a neat idea though.

**Comment by blork** [comment]
I think it would be hard to do it with a single `Requestable` and an array of `Codables`, since you'd have to kind of placeholder part of the Requestable so it could be replaced with the Codable. An array of requestables could work.
